# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 456)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.sb_fractal_depth = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_fractal_depth.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_fractal_depth.setMinimum(1)
        self.sb_fractal_depth.setMaximum(10)
        self.sb_fractal_depth.setObjectName("sb_fractal_depth")
        self.horizontalLayout_3.addWidget(self.sb_fractal_depth)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.dsb_max_line_legth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_max_line_legth.setMinimum(0.01)
        self.dsb_max_line_legth.setMaximum(1.0)
        self.dsb_max_line_legth.setSingleStep(0.01)
        self.dsb_max_line_legth.setProperty("value", 0.05)
        self.dsb_max_line_legth.setObjectName("dsb_max_line_legth")
        self.horizontalLayout_4.addWidget(self.dsb_max_line_legth)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.dsb_angle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_angle.setMinimum(45.0)
        self.dsb_angle.setMaximum(89.0)
        self.dsb_angle.setSingleStep(1.0)
        self.dsb_angle.setProperty("value", 45.0)
        self.dsb_angle.setObjectName("dsb_angle")
        self.horizontalLayout_6.addWidget(self.dsb_angle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.l_image = QtWidgets.QLabel(self.groupBox_2)
        self.l_image.setAlignment(QtCore.Qt.AlignCenter)
        self.l_image.setObjectName("l_image")
        self.verticalLayout_3.addWidget(self.l_image)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.l_single_phase_count_iter_a = QtWidgets.QLabel(self.groupBox_2)
        self.l_single_phase_count_iter_a.setTextFormat(QtCore.Qt.AutoText)
        self.l_single_phase_count_iter_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_single_phase_count_iter_a.setObjectName("l_single_phase_count_iter_a")
        self.horizontalLayout_10.addWidget(self.l_single_phase_count_iter_a)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.sb_single_phase_count_iter_a = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_single_phase_count_iter_a.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_single_phase_count_iter_a.setMinimum(1)
        self.sb_single_phase_count_iter_a.setMaximum(200)
        self.sb_single_phase_count_iter_a.setSingleStep(5)
        self.sb_single_phase_count_iter_a.setProperty("value", 40)
        self.sb_single_phase_count_iter_a.setObjectName("sb_single_phase_count_iter_a")
        self.horizontalLayout_10.addWidget(self.sb_single_phase_count_iter_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_several_phase_count_iter_a = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_count_iter_a.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_count_iter_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_count_iter_a.setObjectName("l_several_phase_count_iter_a")
        self.horizontalLayout_12.addWidget(self.l_several_phase_count_iter_a)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.sb_several_phase_count_iter_a = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_several_phase_count_iter_a.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_several_phase_count_iter_a.setMinimum(1)
        self.sb_several_phase_count_iter_a.setMaximum(200)
        self.sb_several_phase_count_iter_a.setSingleStep(5)
        self.sb_several_phase_count_iter_a.setProperty("value", 40)
        self.sb_several_phase_count_iter_a.setObjectName("sb_several_phase_count_iter_a")
        self.horizontalLayout_12.addWidget(self.sb_several_phase_count_iter_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.l_several_phase_count_iter_b = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_count_iter_b.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_count_iter_b.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_count_iter_b.setObjectName("l_several_phase_count_iter_b")
        self.horizontalLayout_13.addWidget(self.l_several_phase_count_iter_b)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.sb_several_phase_count_iter_b = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_several_phase_count_iter_b.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_several_phase_count_iter_b.setMinimum(1)
        self.sb_several_phase_count_iter_b.setMaximum(200)
        self.sb_several_phase_count_iter_b.setSingleStep(5)
        self.sb_several_phase_count_iter_b.setProperty("value", 40)
        self.sb_several_phase_count_iter_b.setObjectName("sb_several_phase_count_iter_b")
        self.horizontalLayout_13.addWidget(self.sb_several_phase_count_iter_b)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.sb_draw_latency = QtWidgets.QSpinBox(self.groupBox_5)
        self.sb_draw_latency.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_draw_latency.setMinimum(0)
        self.sb_draw_latency.setMaximum(1000)
        self.sb_draw_latency.setSingleStep(100)
        self.sb_draw_latency.setProperty("value", 0)
        self.sb_draw_latency.setObjectName("sb_draw_latency")
        self.horizontalLayout_5.addWidget(self.sb_draw_latency)
        self.horizontalLayout_11.addWidget(self.groupBox_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.rb_single_phase = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_single_phase.setChecked(True)
        self.rb_single_phase.setObjectName("rb_single_phase")
        self.horizontalLayout_7.addWidget(self.rb_single_phase)
        self.rb_several_phase = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_several_phase.setObjectName("rb_several_phase")
        self.horizontalLayout_7.addWidget(self.rb_several_phase)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pb_engender_fractal = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_engender_fractal.setObjectName("pb_engender_fractal")
        self.horizontalLayout_8.addWidget(self.pb_engender_fractal)
        self.pb_build_point_path = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_build_point_path.setObjectName("pb_build_point_path")
        self.horizontalLayout_8.addWidget(self.pb_build_point_path)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_line_color = QtWidgets.QPushButton(self.groupBox)
        self.pb_line_color.setText("")
        self.pb_line_color.setObjectName("pb_line_color")
        self.verticalLayout_2.addWidget(self.pb_line_color)
        self.pb_background_color = QtWidgets.QPushButton(self.groupBox)
        self.pb_background_color.setStyleSheet("QWidget { background-color: rgb(46, 52, 54) }")
        self.pb_background_color.setText("")
        self.pb_background_color.setObjectName("pb_background_color")
        self.verticalLayout_2.addWidget(self.pb_background_color)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 620, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Конфигурация фрактала"))
        self.label.setText(_translate("MainWindow", "Глубина фрактала"))
        self.label_2.setText(_translate("MainWindow", "Max значение длины отрезка"))
        self.label_9.setText(_translate("MainWindow", "Значение угла треугольника"))
        self.l_image.setText(_translate("MainWindow", "Image"))
        self.l_single_phase_count_iter_a.setText(_translate("MainWindow", "<html><head/><body><p>Количество итераций <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.l_several_phase_count_iter_a.setText(_translate("MainWindow", "<html><head/><body><p>Количество итераций <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.l_several_phase_count_iter_b.setText(_translate("MainWindow", "<html><head/><body><p>Количество итераций <span style=\" font-style:italic;\">b</span></p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Дополнительные настройки"))
        self.label_5.setText(_translate("MainWindow", "Задержка при отрисовке, мс"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Построение"))
        self.rb_single_phase.setText(_translate("MainWindow", "Однофазная"))
        self.rb_several_phase.setText(_translate("MainWindow", "Многофазная"))
        self.pb_engender_fractal.setText(_translate("MainWindow", "Фрактал"))
        self.pb_build_point_path.setText(_translate("MainWindow", "Траектория роста точек"))
        self.groupBox.setTitle(_translate("MainWindow", "Палитра цветов"))
        self.label_3.setText(_translate("MainWindow", "Цвет отрезков"))
        self.label_4.setText(_translate("MainWindow", "Цвет фона"))
