# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 570)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_25.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(9, 9, 887, 397))
        self.widget.setObjectName("widget")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_24.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.sb_fractal_depth = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_fractal_depth.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_fractal_depth.setMinimum(1)
        self.sb_fractal_depth.setMaximum(10)
        self.sb_fractal_depth.setObjectName("sb_fractal_depth")
        self.horizontalLayout_3.addWidget(self.sb_fractal_depth)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.dsb_max_line_legth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_max_line_legth.setMinimum(0.01)
        self.dsb_max_line_legth.setMaximum(1.0)
        self.dsb_max_line_legth.setSingleStep(0.01)
        self.dsb_max_line_legth.setProperty("value", 0.05)
        self.dsb_max_line_legth.setObjectName("dsb_max_line_legth")
        self.horizontalLayout_4.addWidget(self.dsb_max_line_legth)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.dsb_angle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_angle.setMinimum(1.0)
        self.dsb_angle.setMaximum(89.0)
        self.dsb_angle.setSingleStep(0.1)
        self.dsb_angle.setProperty("value", 45.0)
        self.dsb_angle.setObjectName("dsb_angle")
        self.horizontalLayout_6.addWidget(self.dsb_angle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.l_image = QtWidgets.QLabel(self.groupBox_2)
        self.l_image.setAlignment(QtCore.Qt.AlignCenter)
        self.l_image.setObjectName("l_image")
        self.verticalLayout_3.addWidget(self.l_image)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_single_phase_count_iterations = QtWidgets.QLabel(self.groupBox_2)
        self.l_single_phase_count_iterations.setTextFormat(QtCore.Qt.AutoText)
        self.l_single_phase_count_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.l_single_phase_count_iterations.setObjectName("l_single_phase_count_iterations")
        self.horizontalLayout_12.addWidget(self.l_single_phase_count_iterations)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.sb_single_phase_count_iterations = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_single_phase_count_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_single_phase_count_iterations.setMinimum(1)
        self.sb_single_phase_count_iterations.setMaximum(200)
        self.sb_single_phase_count_iterations.setSingleStep(5)
        self.sb_single_phase_count_iterations.setProperty("value", 40)
        self.sb_single_phase_count_iterations.setObjectName("sb_single_phase_count_iterations")
        self.horizontalLayout_12.addWidget(self.sb_single_phase_count_iterations)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lb_regular_polygon_count_angle = QtWidgets.QLabel(self.groupBox_2)
        self.lb_regular_polygon_count_angle.setTextFormat(QtCore.Qt.AutoText)
        self.lb_regular_polygon_count_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_regular_polygon_count_angle.setObjectName("lb_regular_polygon_count_angle")
        self.horizontalLayout_13.addWidget(self.lb_regular_polygon_count_angle)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.sb_regular_polygon_count_angle = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_regular_polygon_count_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_regular_polygon_count_angle.setMinimum(3)
        self.sb_regular_polygon_count_angle.setMaximum(40)
        self.sb_regular_polygon_count_angle.setSingleStep(1)
        self.sb_regular_polygon_count_angle.setProperty("value", 3)
        self.sb_regular_polygon_count_angle.setObjectName("sb_regular_polygon_count_angle")
        self.horizontalLayout_13.addWidget(self.sb_regular_polygon_count_angle)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.l_several_phase_coefficient_a = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_coefficient_a.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_coefficient_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_coefficient_a.setObjectName("l_several_phase_coefficient_a")
        self.horizontalLayout_18.addWidget(self.l_several_phase_coefficient_a)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.dsb_several_phase_coefficient_a = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_several_phase_coefficient_a.setMinimum(0.01)
        self.dsb_several_phase_coefficient_a.setMaximum(1.0)
        self.dsb_several_phase_coefficient_a.setSingleStep(0.01)
        self.dsb_several_phase_coefficient_a.setProperty("value", 0.5)
        self.dsb_several_phase_coefficient_a.setObjectName("dsb_several_phase_coefficient_a")
        self.horizontalLayout_18.addWidget(self.dsb_several_phase_coefficient_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.l_several_phase_coefficient_h = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_coefficient_h.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_coefficient_h.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_coefficient_h.setObjectName("l_several_phase_coefficient_h")
        self.horizontalLayout_19.addWidget(self.l_several_phase_coefficient_h)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.dsb_several_phase_coefficient_h = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_several_phase_coefficient_h.setMinimum(0.01)
        self.dsb_several_phase_coefficient_h.setMaximum(1.0)
        self.dsb_several_phase_coefficient_h.setSingleStep(0.01)
        self.dsb_several_phase_coefficient_h.setProperty("value", 0.1)
        self.dsb_several_phase_coefficient_h.setObjectName("dsb_several_phase_coefficient_h")
        self.horizontalLayout_19.addWidget(self.dsb_several_phase_coefficient_h)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.l_several_phase_count_iterations = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_count_iterations.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_count_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_count_iterations.setObjectName("l_several_phase_count_iterations")
        self.horizontalLayout_20.addWidget(self.l_several_phase_count_iterations)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem7)
        self.sb_several_phase_count_iterations = QtWidgets.QSpinBox(self.groupBox_2)
        self.sb_several_phase_count_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_several_phase_count_iterations.setMinimum(1)
        self.sb_several_phase_count_iterations.setMaximum(200)
        self.sb_several_phase_count_iterations.setSingleStep(5)
        self.sb_several_phase_count_iterations.setProperty("value", 40)
        self.sb_several_phase_count_iterations.setObjectName("sb_several_phase_count_iterations")
        self.horizontalLayout_20.addWidget(self.sb_several_phase_count_iterations)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.rb_regular_polygon_build_outside = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_regular_polygon_build_outside.setChecked(True)
        self.rb_regular_polygon_build_outside.setObjectName("rb_regular_polygon_build_outside")
        self.horizontalLayout_14.addWidget(self.rb_regular_polygon_build_outside)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.rb_regular_polygon_build_inside = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_regular_polygon_build_inside.setObjectName("rb_regular_polygon_build_inside")
        self.horizontalLayout_14.addWidget(self.rb_regular_polygon_build_inside)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.pb_calculate_fractal = QtWidgets.QPushButton(self.groupBox_2)
        self.pb_calculate_fractal.setObjectName("pb_calculate_fractal")
        self.verticalLayout_3.addWidget(self.pb_calculate_fractal)
        self.horizontalLayout_24.addWidget(self.groupBox_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.sb_draw_latency = QtWidgets.QSpinBox(self.groupBox_5)
        self.sb_draw_latency.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_draw_latency.setMinimum(0)
        self.sb_draw_latency.setMaximum(1000)
        self.sb_draw_latency.setSingleStep(100)
        self.sb_draw_latency.setProperty("value", 0)
        self.sb_draw_latency.setObjectName("sb_draw_latency")
        self.horizontalLayout_5.addWidget(self.sb_draw_latency)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.sb_thinning_percentage = QtWidgets.QSpinBox(self.groupBox_5)
        self.sb_thinning_percentage.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_thinning_percentage.setMinimum(0)
        self.sb_thinning_percentage.setMaximum(100)
        self.sb_thinning_percentage.setSingleStep(1)
        self.sb_thinning_percentage.setProperty("value", 0)
        self.sb_thinning_percentage.setObjectName("sb_thinning_percentage")
        self.horizontalLayout_10.addWidget(self.sb_thinning_percentage)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem9 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_line_color = QtWidgets.QPushButton(self.groupBox)
        self.pb_line_color.setText("")
        self.pb_line_color.setObjectName("pb_line_color")
        self.verticalLayout_2.addWidget(self.pb_line_color)
        self.pb_background_color = QtWidgets.QPushButton(self.groupBox)
        self.pb_background_color.setStyleSheet("QWidget { background-color: rgb(46, 52, 54) }")
        self.pb_background_color.setText("")
        self.pb_background_color.setObjectName("pb_background_color")
        self.verticalLayout_2.addWidget(self.pb_background_color)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_22.addWidget(self.groupBox)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.cb_screenshot = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_screenshot.setObjectName("cb_screenshot")
        self.horizontalLayout_9.addWidget(self.cb_screenshot)
        spacerItem11 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.pb_screenshot_path = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_screenshot_path.setEnabled(False)
        self.pb_screenshot_path.setObjectName("pb_screenshot_path")
        self.verticalLayout_6.addWidget(self.pb_screenshot_path)
        self.horizontalLayout_22.addWidget(self.groupBox_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rb_single_phase = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_single_phase.setChecked(True)
        self.rb_single_phase.setObjectName("rb_single_phase")
        self.horizontalLayout_7.addWidget(self.rb_single_phase)
        self.rb_several_phases = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_several_phases.setObjectName("rb_several_phases")
        self.horizontalLayout_7.addWidget(self.rb_several_phases)
        self.rb_regular_polygon = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_regular_polygon.setObjectName("rb_regular_polygon")
        self.horizontalLayout_7.addWidget(self.rb_regular_polygon)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pb_visualize = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_visualize.setObjectName("pb_visualize")
        self.horizontalLayout_8.addWidget(self.pb_visualize)
        self.pb_build_point_path = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_build_point_path.setObjectName("pb_build_point_path")
        self.horizontalLayout_8.addWidget(self.pb_build_point_path)
        self.pb_thin_out = QtWidgets.QPushButton(self.groupBox_4)
        self.pb_thin_out.setObjectName("pb_thin_out")
        self.horizontalLayout_8.addWidget(self.pb_thin_out)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.horizontalLayout_24.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_23.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.lb_graph_line_len = QtWidgets.QLabel(self.groupBox_3)
        self.lb_graph_line_len.setObjectName("lb_graph_line_len")
        self.horizontalLayout_17.addWidget(self.lb_graph_line_len)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.pb_graph_line_len = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_graph_line_len.setObjectName("pb_graph_line_len")
        self.horizontalLayout_17.addWidget(self.pb_graph_line_len)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.lb_graph_line_len_one_and_several_phases = QtWidgets.QLabel(self.groupBox_3)
        self.lb_graph_line_len_one_and_several_phases.setObjectName("lb_graph_line_len_one_and_several_phases")
        self.horizontalLayout_21.addWidget(self.lb_graph_line_len_one_and_several_phases)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem13)
        self.pb_graph_line_len_one_and_several_phases = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_graph_line_len_one_and_several_phases.setObjectName("pb_graph_line_len_one_and_several_phases")
        self.horizontalLayout_21.addWidget(self.pb_graph_line_len_one_and_several_phases)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lb_graph_scale = QtWidgets.QLabel(self.groupBox_3)
        self.lb_graph_scale.setObjectName("lb_graph_scale")
        self.horizontalLayout_16.addWidget(self.lb_graph_scale)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.pb_graph_scale = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_graph_scale.setObjectName("pb_graph_scale")
        self.horizontalLayout_16.addWidget(self.pb_graph_scale)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lb_graph_scale_one_and_several_phases = QtWidgets.QLabel(self.groupBox_3)
        self.lb_graph_scale_one_and_several_phases.setObjectName("lb_graph_scale_one_and_several_phases")
        self.horizontalLayout_15.addWidget(self.lb_graph_scale_one_and_several_phases)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem15)
        self.pb_graph_scale_one_and_several_phases = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_graph_scale_one_and_several_phases.setObjectName("pb_graph_scale_one_and_several_phases")
        self.horizontalLayout_15.addWidget(self.pb_graph_scale_one_and_several_phases)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lb_graph_angle = QtWidgets.QLabel(self.groupBox_3)
        self.lb_graph_angle.setObjectName("lb_graph_angle")
        self.horizontalLayout_11.addWidget(self.lb_graph_angle)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.pb_graph_angle = QtWidgets.QPushButton(self.groupBox_3)
        self.pb_graph_angle.setObjectName("pb_graph_angle")
        self.horizontalLayout_11.addWidget(self.pb_graph_angle)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_23.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_25.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 942, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Фрактальная структура - Кривая Коха"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Конфигурация фрактала"))
        self.label.setText(_translate("MainWindow", "Глубина фрактала"))
        self.label_2.setText(_translate("MainWindow", "Max значение длины отрезка"))
        self.label_9.setText(_translate("MainWindow", "Значение угла треугольника"))
        self.l_image.setText(_translate("MainWindow", "Image"))
        self.l_single_phase_count_iterations.setText(_translate("MainWindow", "<html><head/><body><p>Количество итераций роста отрезка <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.lb_regular_polygon_count_angle.setText(_translate("MainWindow", "<html><head/><body><p>Количество углов правильной фигуры</p></body></html>"))
        self.l_several_phase_coefficient_a.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент начальной длины отрезка <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.l_several_phase_coefficient_h.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент начальной длины отрезка <span style=\" font-style:italic;\">h</span></p></body></html>"))
        self.l_several_phase_count_iterations.setText(_translate("MainWindow", "<html><head/><body><p>Количество итераций роста отрезков <span style=\" font-style:italic;\">a </span>и <span style=\" font-style:italic;\">b</span></p></body></html>"))
        self.rb_regular_polygon_build_outside.setText(_translate("MainWindow", "Строить снаружи"))
        self.rb_regular_polygon_build_inside.setText(_translate("MainWindow", "Строить внутрь"))
        self.pb_calculate_fractal.setText(_translate("MainWindow", "Вычислить"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Дополнительные настройки"))
        self.label_5.setText(_translate("MainWindow", "Задержка при отрисовке, мс"))
        self.label_6.setText(_translate("MainWindow", "Процент прореживания, %"))
        self.groupBox.setTitle(_translate("MainWindow", "Палитра цветов"))
        self.label_3.setText(_translate("MainWindow", "Цвет отрезков"))
        self.label_4.setText(_translate("MainWindow", "Цвет фона"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Экспорт изображений"))
        self.cb_screenshot.setText(_translate("MainWindow", "Сохранить"))
        self.pb_screenshot_path.setText(_translate("MainWindow", "Указать путь..."))
        self.groupBox_4.setTitle(_translate("MainWindow", "Построение модели"))
        self.rb_single_phase.setText(_translate("MainWindow", "Однофазная"))
        self.rb_several_phases.setText(_translate("MainWindow", "Многофазная"))
        self.rb_regular_polygon.setText(_translate("MainWindow", "Правильная фигура"))
        self.pb_visualize.setText(_translate("MainWindow", "Визуализировать"))
        self.pb_build_point_path.setText(_translate("MainWindow", "Траектория роста точек"))
        self.pb_thin_out.setText(_translate("MainWindow", "Проредить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Визуализация"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Построение графиков зависимостей"))
        self.lb_graph_line_len.setText(_translate("MainWindow", "Длина фрактала от количества фаз"))
        self.pb_graph_line_len.setText(_translate("MainWindow", "Построить"))
        self.lb_graph_line_len_one_and_several_phases.setText(_translate("MainWindow", "Длина фрактала от количества фаз в однофазной и многофазной модели"))
        self.pb_graph_line_len_one_and_several_phases.setText(_translate("MainWindow", "Построить"))
        self.lb_graph_scale.setText(_translate("MainWindow", "Масштаб фрактала от количества фаз"))
        self.pb_graph_scale.setText(_translate("MainWindow", "Построить"))
        self.lb_graph_scale_one_and_several_phases.setText(_translate("MainWindow", "Масштаб фрактала от количества фаз в однофазной и многофазной модели"))
        self.pb_graph_scale_one_and_several_phases.setText(_translate("MainWindow", "Построить"))
        self.lb_graph_angle.setText(_translate("MainWindow", "Значение углов от количества фаз"))
        self.pb_graph_angle.setText(_translate("MainWindow", "Построить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Аналитика"))
