# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'one_and_several_phases_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 325)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.sb_fractal_depth = QtWidgets.QSpinBox(self.groupBox)
        self.sb_fractal_depth.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_fractal_depth.setMinimum(1)
        self.sb_fractal_depth.setMaximum(10)
        self.sb_fractal_depth.setObjectName("sb_fractal_depth")
        self.horizontalLayout_3.addWidget(self.sb_fractal_depth)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.dsb_max_line_legth = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_max_line_legth.setMinimum(0.01)
        self.dsb_max_line_legth.setMaximum(1.0)
        self.dsb_max_line_legth.setSingleStep(0.01)
        self.dsb_max_line_legth.setProperty("value", 0.05)
        self.dsb_max_line_legth.setObjectName("dsb_max_line_legth")
        self.horizontalLayout_4.addWidget(self.dsb_max_line_legth)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.l_count_iterations = QtWidgets.QLabel(self.groupBox)
        self.l_count_iterations.setTextFormat(QtCore.Qt.AutoText)
        self.l_count_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.l_count_iterations.setObjectName("l_count_iterations")
        self.horizontalLayout_12.addWidget(self.l_count_iterations)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.sb_count_iterations = QtWidgets.QSpinBox(self.groupBox)
        self.sb_count_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.sb_count_iterations.setMinimum(1)
        self.sb_count_iterations.setMaximum(200)
        self.sb_count_iterations.setSingleStep(5)
        self.sb_count_iterations.setProperty("value", 40)
        self.sb_count_iterations.setObjectName("sb_count_iterations")
        self.horizontalLayout_12.addWidget(self.sb_count_iterations)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.dsb_angle = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_angle.setMinimum(1.0)
        self.dsb_angle.setMaximum(89.0)
        self.dsb_angle.setSingleStep(0.1)
        self.dsb_angle.setProperty("value", 45.0)
        self.dsb_angle.setObjectName("dsb_angle")
        self.horizontalLayout_6.addWidget(self.dsb_angle)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.lb_image_one_phase = QtWidgets.QLabel(self.groupBox)
        self.lb_image_one_phase.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_image_one_phase.setObjectName("lb_image_one_phase")
        self.verticalLayout.addWidget(self.lb_image_one_phase)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_several_phases = QtWidgets.QVBoxLayout()
        self.layout_several_phases.setSpacing(6)
        self.layout_several_phases.setObjectName("layout_several_phases")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.l_several_phase_coefficient_a = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_coefficient_a.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_coefficient_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_coefficient_a.setObjectName("l_several_phase_coefficient_a")
        self.horizontalLayout_18.addWidget(self.l_several_phase_coefficient_a)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.dsb_several_phase_coefficient_a = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_several_phase_coefficient_a.setMinimum(0.01)
        self.dsb_several_phase_coefficient_a.setMaximum(1.0)
        self.dsb_several_phase_coefficient_a.setSingleStep(0.01)
        self.dsb_several_phase_coefficient_a.setProperty("value", 0.5)
        self.dsb_several_phase_coefficient_a.setObjectName("dsb_several_phase_coefficient_a")
        self.horizontalLayout_18.addWidget(self.dsb_several_phase_coefficient_a)
        self.layout_several_phases.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.l_several_phase_coefficient_h = QtWidgets.QLabel(self.groupBox_2)
        self.l_several_phase_coefficient_h.setTextFormat(QtCore.Qt.AutoText)
        self.l_several_phase_coefficient_h.setAlignment(QtCore.Qt.AlignCenter)
        self.l_several_phase_coefficient_h.setObjectName("l_several_phase_coefficient_h")
        self.horizontalLayout_19.addWidget(self.l_several_phase_coefficient_h)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.dsb_several_phase_coefficient_h = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsb_several_phase_coefficient_h.setMinimum(0.01)
        self.dsb_several_phase_coefficient_h.setMaximum(1.0)
        self.dsb_several_phase_coefficient_h.setSingleStep(0.01)
        self.dsb_several_phase_coefficient_h.setProperty("value", 0.1)
        self.dsb_several_phase_coefficient_h.setObjectName("dsb_several_phase_coefficient_h")
        self.horizontalLayout_19.addWidget(self.dsb_several_phase_coefficient_h)
        self.layout_several_phases.addLayout(self.horizontalLayout_19)
        self.verticalLayout_2.addLayout(self.layout_several_phases)
        self.lb_image_several_phases = QtWidgets.QLabel(self.groupBox_2)
        self.lb_image_several_phases.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_image_several_phases.setObjectName("lb_image_several_phases")
        self.verticalLayout_2.addWidget(self.lb_image_several_phases)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.pb_calculate_fractal = QtWidgets.QPushButton(self.centralWidget)
        self.pb_calculate_fractal.setObjectName("pb_calculate_fractal")
        self.horizontalLayout_2.addWidget(self.pb_calculate_fractal)
        spacerItem7 = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 842, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Зависимость длины фрактальной линии от циклов"))
        self.groupBox.setTitle(_translate("MainWindow", "Общие настройки"))
        self.label.setText(_translate("MainWindow", "Глубина фрактала"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Max значение длины отрезка <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.l_count_iterations.setText(_translate("MainWindow", "<html><head/><body><p>Количество итераций роста отрезка <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Значение угла треугольника"))
        self.lb_image_one_phase.setText(_translate("MainWindow", "Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Настройки для многофазной модели"))
        self.l_several_phase_coefficient_a.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент начальной длины отрезка <span style=\" font-style:italic;\">a</span></p></body></html>"))
        self.l_several_phase_coefficient_h.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент начальной длины отрезка <span style=\" font-style:italic;\">h</span></p></body></html>"))
        self.lb_image_several_phases.setText(_translate("MainWindow", "Image"))
        self.pb_calculate_fractal.setText(_translate("MainWindow", "Вычислить"))
